language: php
sudo: false
php:
 - 5.3

env:
 - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.4
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.5
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=1
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=master
  allow_failures:
    - env: DB=MYSQL CORE_RELEASE=3.2
    - env: DB=MYSQL CORE_RELEASE=master

before_script:
 - pear -q install --onlyreqdeps pear/PHP_CodeSniffer
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: ~/build/ss/cloudassets/tests/travis/run_build.sh

after_script: ~/build/ss/cloudassets/test/travis/upload_coverage.sh
